# Generated by Django 2.2.7 on 2019-12-06 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('asn_per', models.IntegerField()),
                ('twenty_per', models.IntegerField()),
                ('fdn_per', models.IntegerField()),
                ('svc_per', models.IntegerField()),
                ('ucd_per', models.IntegerField()),
                ('sp_per', models.IntegerField()),
                ('tv_per', models.IntegerField()),
                ('accountant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
